# Generated by Django 4.2.13 on 2024-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Unknown')], verbose_name='Gender'),
        ),
    ]
