# Generated by Django 4.2.13 on 2024-07-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_dob_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, verbose_name='mobile')),
                ('price', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='price')),
                ('level', models.SmallIntegerField(choices=[(2, 'Sliver Member'), (1, 'Normal Member'), (4, 'Primer Member '), (3, 'Golden Member')], verbose_name='level')),
                ('state', models.SmallIntegerField(choices=[(1, 'Used'), (2, 'Not Used')], verbose_name='State')),
            ],
        ),
    ]
