# Generated by Django 4.2.13 on 2024-07-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_prettynum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Normal Member'), (4, 'Primer Member '), (3, 'Golden Member'), (2, 'Sliver Member')], verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
    ]
