# Generated by Django 4.2.13 on 2024-07-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_prettynum_level_alter_prettynum_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Normal Member'), (2, 'Sliver Member'), (3, 'Golden Member'), (4, 'Primer Member ')], verbose_name='level'),
        ),
    ]
