# Generated by Django 4.2.13 on 2024-07-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_prettynum_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(2, 'Sliver Member'), (1, 'Normal Member'), (4, 'Primer Member '), (3, 'Golden Member')], verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
    ]
